relativeURLs = true
title = "Jitendra Aswani"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. Candidate in Business Economics, Fordham University"
    logo = "jeetprofilepic1.jpg" 
    
