relativeURLs = true
title = "Jitendra Aswani"
theme = "academimal1"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = ""
    logo = "jeetprofilepic2.jpg" 
    
