relativeURLs = true
title = "Gautam Rao"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo" ]

[params]
    shortbio = "Assistant Professor of Economics, Harvard University"
    logo = "gr.jpg" 
    
